# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site ç«™ç‚¹ä¿¡æ¯è®¾ç½®
title: ğ“—ğ“¸ğ“¼ğ“±ğ“²ğ”ƒğ“¸ğ“»ğ“ª #ç«™å
subtitle: å¸Œæœ›é˜³å…‰å¾ˆæš–ï¼Œå¾®é£ä¸ç‡¥ï¼Œæ—¶å…‰ä¸è€ï¼Œä½ æˆ‘éƒ½å¥½ã€‚ #å‰¯æ ‡é¢˜
description: #ç«™æè¿°
keywords:
author: ğ•®ğ–ğ–Šğ–“ #ä½œè€…
language: zh-CN #è¯­è¨€
timezone:

# URL é“¾æ¥è®¾ç½®
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://cxyzzz.gtihub.io
root: /
permalink: posts/:abbrlink.html #:title.html
permalink_defaults: posts/:title.html

# Directory æ–‡ä»¶ç›®å½•
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - '*.html'
  - '*.json'
  - '*.txt'

# Writing æ–‡ç« 
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format æ—¥æœŸ
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination åˆ†é¡µ
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
    
# Extensions æ‰©å±•
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
plugins:
    hexo-generator-feed
    hexo-footnotes
    hexo-generator-sitemap
    hexo-generator-baidu-sitemap
        
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository:
    github: git@github.com:cxyzzz/cxyzzz.github.io.git
    coding: git@git.coding.net:Virgo-233/Virgo-233.git
  branch: master
- type: baidu_url_submitter
- type: leancloud_counter_security_sync
  message: 'ç«™ç‚¹æ›´æ–°:{{now("YYYY-MM-DD HH/mm/ss")}}'

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

leancloud_counter_security:
  enable_sync: true
  app_id: W0aszG0X0SsIHQvIWYSrC969-gzGzoHsz
  app_key: ozjSCfjt66qIMInckgP8YzkB
  username: virgo
  password: lucky

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

nofollow:
    enable: true
	  exclude:
      - hbh.fun
      - ltccc.top
      - www.hojun.cn
      - firstkaixin.github.io

# èµ„æºå‹ç¼©
all_minifier: true
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  use_versioned_bundle: false
  front: false

html_minifier:
  enable: false
  ignore_error: false
  exclude: 

image_minifier:
  enable: true
  interlaced: false
  multipass: true
  optimizationLevel: 5
  pngquant: true
  progressive: false

js_minifier:
  enable: true
  mangle: true
  output: 
  compress:
  exclude:
    - '*.min.js'

css_minifier:
  enable: true
  exclude:
    - '*.min.css'
 
baidu_url_submit:
  count: 20 # æäº¤æœ€æ–°çš„é“¾æ¥
  host: blog.timelless.xyz # åœ¨ç™¾åº¦ç«™é•¿å¹³å°ä¸­æ³¨å†Œçš„åŸŸå
  token: X0OAPF42bzanVSC8 # è¯·æ³¨æ„è¿™æ˜¯æ‚¨çš„ç§˜é’¥ï¼Œ æ‰€ä»¥è¯·ä¸è¦æŠŠåšå®¢æºä»£ç å‘å¸ƒåœ¨å…¬ä¼—ä»“åº“é‡Œ!
  path: baidu_urls.txt # æ–‡æœ¬æ–‡æ¡£çš„åœ°å€ï¼Œ æ–°é“¾æ¥ä¼šä¿å­˜åœ¨æ­¤æ–‡æœ¬æ–‡æ¡£é‡Œ

popularPosts:
  googleAnalyticsAPI:
    clientId: blog-312@blog-208111.iam.gserviceaccount.com
    serviceEmail: blog-312@blog-208111.iam.gserviceaccount.com
    key: /google-services-private-key.pem
    viewId: 174593295  

# abbrlink config
abbrlink:
  alg: crc32  # ç®—æ³•ï¼šcrc16(default) and crc32 
  rep: hex    # è¿›åˆ¶ï¼šdec(default) and hex

auto_dir_categorize:
	enable: true  # options:true, false; default is true
	force: false # options:true, false; default is false

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
  sanitizeUrl: false
  headerIds: true

# Security
encrypt: # hexo-blog-encrypt
  enable: true
